-- liquibase formatted sql

-- changeset Berk:1725744204078-1

CREATE TABLE credits
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    principal_amount DECIMAL                                 NOT NULL,
    total_amount     DECIMAL                                 NOT NULL,
    interest_rate    BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    CONSTRAINT "pk_credıts" PRIMARY KEY (id)
);

CREATE TABLE installments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    credit_id          BIGINT                                  NOT NULL,
    installment_id     INTEGER                                 NOT NULL,
    amount             DECIMAL                                 NOT NULL,
    due_date           date                                    NOT NULL,
    overdue_days       INTEGER                                 NOT NULL,
    overdue_fee_amount DECIMAL                                 NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    CONSTRAINT "pk_ınstallments" PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    installment_id BIGINT                                  NOT NULL,
    paid_amount    DECIMAL,
    payment_date   TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(255),
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    address      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT "uc_users_emaıl" UNIQUE (email);

ALTER TABLE credits
    ADD CONSTRAINT FK_CREDITS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE installments
    ADD CONSTRAINT FK_INSTALLMENTS_ON_CREDIT FOREIGN KEY (credit_id) REFERENCES credits (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_INSTALLMENT FOREIGN KEY (installment_id) REFERENCES installments (id);


-- changeset Berk:1725744204078-2

INSERT INTO public.users (created_at, updated_at, address, email, first_name, last_name, phone_number)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '123 Main St', 'john.doe@example.com', 'John', 'Doe', '555-0100'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '456 Elm St', 'jane.doe@example.com', 'Jane', 'Doe', '555-0101'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '789 Oak St', 'alice.smith@example.com', 'Alice', 'Smith', '555-0102'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '101 Pine St', 'bob.johnson@example.com', 'Bob', 'Johnson', '555-0103'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '202 Maple St', 'charlie.brown@example.com', 'Charlie', 'Brown',
        '555-0104');
